### ISSUE TITLE
Problem with Features to GPX 10.1

### ISSUE THREAD

**Issue by andybeanit** [arcpy/sample-gp-tools#12]
Hi, is there a way to dictate which field from your attribute table is used to label the output points in your GPX? By default it spits out points with labels based on the OBJECTID field, but this is not the name of the point that is useful in Garmin Basecamp nor on the ground using GPS units. Thanks!

Andy

**Comment by khibma** [comment]
Hi Andy, I don't recall the code specifically looking for OBJECTID when making the GPX file.

Looking at the code, my assumption is your data does NOT have a **name** field (that and Garmin Basecamp looks for a name field within the GPX). The tool's code specifically looks for that **name** field and when it finds it, uses that value to make the **name** value in the gpx file.
eg. https://github.com/arcpy/sample-gp-tools/blob/master/FeaturesToGPX/FeaturesToGPX.py#L91

Could you try making a new field in your data, **name**, and calculating the value of that from an appropriate field in your data?
