### ISSUE TITLE
FeaturesToGPX Toolbox Not Loading in Arc

### ISSUE THREAD

**Issue by sheilasaia** [arcpy/sample-gp-tools#3]
Dear Kevin,

Thanks so much for creating this script!  It's such a great idea and will make it so much easier to do this in Arc.  I'm having trouble getting FeaturesToGPS to show up on my Arc ToolBox and might have missed something.  I downloaded your python script and and .tbx files and added them to the ArcGIS "Toolboxes" program folder but when I import the toolbox, the tool isn't showing up in a usable way.  If it's easier to explain over email, you can find me at sms493 at cornell dot edu.

Thanks again!
Sheila

**Comment by khibma** [comment]
Sorry, I am just seeing this now. To use the tool, you have 2 options. You can deploy them with the setup, which will make a new toolbox inside your ArcToolbox. Alternatively, if you simply download the zip file and extract, you can navigate using the Catalog window to that location and run the tool from there. Either the samples.tbx or go into the FeaturesToGPX folder and run that specific tool.

**Comment by GeoCanuck** [comment]
I cannot seem to load the FeaturesToGPX tool, or rather the part I was looking for.

As I understood the documentation, you can convert a line/point shape to a GPX file, which is what I was looking for.

However, when I load the tool into Arc, I can only load GPX files into Arc, which is useless to me.

This is what I see when I open the Add-In Controls tool to drag the toolset to my toolbar, just "GPX Import":
![featuretogpx loading](https://cloud.githubusercontent.com/assets/19158537/14970953/523cf420-1082-11e6-9086-012d127be17b.jpg)

Where is the FeatureToGPX that I was looking for?

**Comment by khibma** [comment]
@GeoCanuck this is a tool, not an add in. As such just navigate to the folder you unzipped to in the Contents window and open the toolbox.  Or open the ArcToolbox, right click and add which will allow you to navigate to the toolbox.

**Comment by GeoCanuck** [comment]
I have never added tools before, so am not sure how it is done.
I just followed installation instructions, but now cannot find them to check. 
However, all I got was the wrong tool. Even though the downloaded zipfile contents say FeaturestoGPX, I just seem to get GPXToFeatures
